name: Scheduled Commit  
on:
  schedule:
    - cron: "0 12 22-25 2 *"  # Runs at 12:00 UTC on Feb 22, 23, 24, and 25 (2025)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a dummy commit
        run: |
          date > commit.txt
          git config --global user.email "afzaldeveloper7@gmail.com"
          git config --global user.name "Afzalfaizi"
          git add commit.txt
          git commit -m "Automated commit to keep streak"
          git push
